[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = [
    "pip install -e .",
    "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn stocksignal.api.main:app --host 0.0.0.0 --port $PORT"